/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : PTC13_14_15.c
**     Project     : Ms_200
**     Processor   : MK20DX256VLL7
**     Component   : BitsIO
**     Version     : Component 02.108, Driver 01.00, CPU db: 3.00.000
**     Repository  : Kinetis
**     Compiler    : GNU C Compiler
**     Date/Time   : 2018-11-12, 19:37, # CodeGen: 213
**     Abstract    :
**         This component "BitsIO" implements a multi-bit input/output.
**         It uses selected pins of one 1-bit to 8-bit port.
**         Note: This component is set to work in Output direction only.
**     Settings    :
**          Component name                                 : PTC13_14_15
**          Port                                           : PTC
**          BitsIO_LDD                                     : BitsIO_LDD
**          Pins                                           : 3
**            Pin0                                         : 
**              Pin                                        : PTC13/UART4_CTS_b/FB_AD26
**              Pin signal                                 : 
**            Pin1                                         : 
**              Pin                                        : PTC14/UART4_RX/FB_AD25
**              Pin signal                                 : 
**            Pin2                                         : 
**              Pin                                        : PTC15/UART4_TX/FB_AD24
**              Pin signal                                 : 
**          Direction                                      : Output
**          Initialization                                 : 
**            Init. direction                              : Output
**            Init. value                                  : 0
**          Safe mode                                      : yes
**          Optimization for                               : speed
**     Contents    :
**         GetDir - bool PTC13_14_15_GetDir(void);
**         GetVal - byte PTC13_14_15_GetVal(void);
**         PutVal - void PTC13_14_15_PutVal(byte Val);
**         GetBit - bool PTC13_14_15_GetBit(byte Bit);
**         PutBit - void PTC13_14_15_PutBit(byte Bit, bool Val);
**         SetBit - void PTC13_14_15_SetBit(byte Bit);
**         ClrBit - void PTC13_14_15_ClrBit(byte Bit);
**         NegBit - void PTC13_14_15_NegBit(byte Bit);
**
**     Copyright : 1997 - 2015 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file PTC13_14_15.c
** @version 01.00
** @brief
**         This component "BitsIO" implements a multi-bit input/output.
**         It uses selected pins of one 1-bit to 8-bit port.
**         Note: This component is set to work in Output direction only.
*/         
/*!
**  @addtogroup PTC13_14_15_module PTC13_14_15 module documentation
**  @{
*/         

/* MODULE PTC13_14_15. */

#include "PTC13_14_15.h"

#ifdef __cplusplus
extern "C" {
#endif 

/*
** ===================================================================
**     Method      :  PTC13_14_15_GetDir (component BitsIO)
**     Description :
**         This method returns direction of the component.
**     Parameters  : None
**     Returns     :
**         ---        - Direction of the component (always <true>, Output only)
**                      <false> = Input, <true> = Output
** ===================================================================
*/
/*
bool PTC13_14_15_GetDir(void)

**  This method is implemented as a macro. See PTC13_14_15.h file.  **
*/

/*
** ===================================================================
**     Method      :  PTC13_14_15_GetVal (component BitsIO)
**     Description :
**         This method returns an input value.
**           a) direction = Input  : reads the input value from the
**                                   pins and returns it
**           b) direction = Output : returns the last written value
**         Note: This component is set to work in Output direction only.
**     Parameters  : None
**     Returns     :
**         ---        - Input value (0 to 7)
** ===================================================================
*/
/*
byte PTC13_14_15_GetVal(void)

**  This method is implemented as a macro. See PTC13_14_15.h file.  **
*/

/*
** ===================================================================
**     Method      :  PTC13_14_15_PutVal (component BitsIO)
**     Description :
**         This method writes the new output value.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Val        - Output value (0 to 7)
**     Returns     : Nothing
** ===================================================================
*/
/*
void PTC13_14_15_PutVal(byte Val)

**  This method is implemented as a macro. See PTC13_14_15.h file.  **
*/

/*
** ===================================================================
**     Method      :  PTC13_14_15_GetBit (component BitsIO)
**     Description :
**         This method returns the specified bit of the input value.
**           a) direction = Input  : reads the input value from pins
**                                   and returns the specified bit
**           b) direction = Output : returns the specified bit
**                                   of the last written value
**         Note: This component is set to work in Output direction only.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit to read (0 to 2)
**     Returns     :
**         ---        - Value of the specified bit (FALSE or TRUE)
**                      FALSE = "0" or "Low", TRUE = "1" or "High"
** ===================================================================
*/
bool PTC13_14_15_GetBit(byte Bit)
{
  bool BitVal;

  (void)BitsIoLdd3_GetBit(BitsIoLdd3_DeviceData, Bit, &BitVal);
  return (BitVal);
}

/*
** ===================================================================
**     Method      :  PTC13_14_15_PutBit (component BitsIO)
**     Description :
**         This method writes the new value to the specified bit
**         of the output value.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit (0 to 2)
**         Val        - New value of the bit (FALSE or TRUE)
**                      FALSE = "0" or "Low", TRUE = "1" or "High"
**     Returns     : Nothing
** ===================================================================
*/
/*
void PTC13_14_15_PutBit(byte Bit, bool Val)

**  This method is implemented as a macro. See PTC13_14_15.h file.  **
*/

/*
** ===================================================================
**     Method      :  PTC13_14_15_SetBit (component BitsIO)
**     Description :
**         This method sets (sets to one) the specified bit of the
**         output value.
**         [ It is the same as "PutBit(Bit,TRUE);" ]
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit to set (0 to 2)
**     Returns     : Nothing
** ===================================================================
*/
/*
void PTC13_14_15_SetBit(byte Bit)

**  This method is implemented as a macro. See PTC13_14_15.h file.  **
*/

/*
** ===================================================================
**     Method      :  PTC13_14_15_ClrBit (component BitsIO)
**     Description :
**         This method clears (sets to zero) the specified bit
**         of the output value.
**         [ It is the same as "PutBit(Bit,FALSE);" ]
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit to clear (0 to 2)
**     Returns     : Nothing
** ===================================================================
*/
/*
void PTC13_14_15_ClrBit(byte Bit)

**  This method is implemented as a macro. See PTC13_14_15.h file.  **
*/

/*
** ===================================================================
**     Method      :  PTC13_14_15_NegBit (component BitsIO)
**     Description :
**         This method negates (inverts) the specified bit of the
**         output value.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit to invert (0 to 31)
**     Returns     : Nothing
** ===================================================================
*/
/*
void PTC13_14_15_NegBit(byte Bit)

**  This method is implemented as a macro. See PTC13_14_15.h file.  **
*/

/* END PTC13_14_15. */

#ifdef __cplusplus
}  /* extern "C" */
#endif 

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
