/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : PTES.h
**     Project     : Ms_200
**     Processor   : MK20DX256VLL7
**     Component   : BitsIO
**     Version     : Component 02.108, Driver 01.00, CPU db: 3.00.000
**     Repository  : Kinetis
**     Compiler    : GNU C Compiler
**     Date/Time   : 2018-11-12, 19:37, # CodeGen: 213
**     Abstract    :
**         This component "BitsIO" implements a multi-bit input/output.
**         It uses selected pins of one 1-bit to 8-bit port.
**         Note: This component is set to work in Output direction only.
**     Settings    :
**          Component name                                 : PTES
**          Port                                           : PTE
**          BitsIO_LDD                                     : BitsIO_LDD
**          Pins                                           : 4
**            Pin0                                         : 
**              Pin                                        : ADC1_SE7a/PTE3/SPI1_SIN/UART1_RTS_b/SPI1_SOUT
**              Pin signal                                 : 
**            Pin1                                         : 
**              Pin                                        : PTE4/LLWU_P2/SPI1_PCS0/UART3_TX
**              Pin signal                                 : 
**            Pin2                                         : 
**              Pin                                        : PTE5/SPI1_PCS2/UART3_RX
**              Pin signal                                 : 
**            Pin3                                         : 
**              Pin                                        : PTE6/SPI1_PCS3/UART3_CTS_b/I2S0_MCLK/USB_SOF_OUT
**              Pin signal                                 : 
**          Direction                                      : Output
**          Initialization                                 : 
**            Init. direction                              : Output
**            Init. value                                  : 0
**          Safe mode                                      : yes
**          Optimization for                               : speed
**     Contents    :
**         GetDir - bool PTES_GetDir(void);
**         GetVal - byte PTES_GetVal(void);
**         PutVal - void PTES_PutVal(byte Val);
**         GetBit - bool PTES_GetBit(byte Bit);
**         PutBit - void PTES_PutBit(byte Bit, bool Val);
**         SetBit - void PTES_SetBit(byte Bit);
**         ClrBit - void PTES_ClrBit(byte Bit);
**         NegBit - void PTES_NegBit(byte Bit);
**
**     Copyright : 1997 - 2015 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file PTES.h
** @version 01.00
** @brief
**         This component "BitsIO" implements a multi-bit input/output.
**         It uses selected pins of one 1-bit to 8-bit port.
**         Note: This component is set to work in Output direction only.
*/         
/*!
**  @addtogroup PTES_module PTES module documentation
**  @{
*/         

#ifndef __PTES_H
#define __PTES_H

/* MODULE PTES. */

/* Include shared modules, which are used for whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
/* Include inherited beans */
#include "BitsIoLdd4.h"

#include "Cpu.h"

#ifdef __cplusplus
extern "C" {
#endif 




/*
** ===================================================================
**     Method      :  PTES_GetDir (component BitsIO)
**     Description :
**         This method returns direction of the component.
**     Parameters  : None
**     Returns     :
**         ---        - Direction of the component (always <true>, Output only)
**                      <false> = Input, <true> = Output
** ===================================================================
*/
#define PTES_GetDir() (BitsIoLdd4_GetDir(BitsIoLdd4_DeviceData))

/*
** ===================================================================
**     Method      :  PTES_GetVal (component BitsIO)
**     Description :
**         This method returns an input value.
**           a) direction = Input  : reads the input value from the
**                                   pins and returns it
**           b) direction = Output : returns the last written value
**         Note: This component is set to work in Output direction only.
**     Parameters  : None
**     Returns     :
**         ---        - Input value (0 to 15)
** ===================================================================
*/
#define PTES_GetVal() ((byte)BitsIoLdd4_GetVal(BitsIoLdd4_DeviceData))

/*
** ===================================================================
**     Method      :  PTES_PutVal (component BitsIO)
**     Description :
**         This method writes the new output value.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Val        - Output value (0 to 15)
**     Returns     : Nothing
** ===================================================================
*/
#define PTES_PutVal(Val) (BitsIoLdd4_PutVal(BitsIoLdd4_DeviceData, ((dword)(Val))))

bool PTES_GetBit(byte Bit);
/*
** ===================================================================
**     Method      :  PTES_GetBit (component BitsIO)
**     Description :
**         This method returns the specified bit of the input value.
**           a) direction = Input  : reads the input value from pins
**                                   and returns the specified bit
**           b) direction = Output : returns the specified bit
**                                   of the last written value
**         Note: This component is set to work in Output direction only.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit to read (0 to 3)
**     Returns     :
**         ---        - Value of the specified bit (FALSE or TRUE)
**                      FALSE = "0" or "Low", TRUE = "1" or "High"
** ===================================================================
*/

/*
** ===================================================================
**     Method      :  PTES_PutBit (component BitsIO)
**     Description :
**         This method writes the new value to the specified bit
**         of the output value.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit (0 to 3)
**         Val        - New value of the bit (FALSE or TRUE)
**                      FALSE = "0" or "Low", TRUE = "1" or "High"
**     Returns     : Nothing
** ===================================================================
*/
#define PTES_PutBit(Bit,Val) ((void)BitsIoLdd4_PutBit(BitsIoLdd4_DeviceData, (Bit), (Val)))

/*
** ===================================================================
**     Method      :  PTES_SetBit (component BitsIO)
**     Description :
**         This method sets (sets to one) the specified bit of the
**         output value.
**         [ It is the same as "PutBit(Bit,TRUE);" ]
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit to set (0 to 3)
**     Returns     : Nothing
** ===================================================================
*/
#define PTES_SetBit(Bit) ((void)BitsIoLdd4_SetBit(BitsIoLdd4_DeviceData, (Bit)))

/*
** ===================================================================
**     Method      :  PTES_ClrBit (component BitsIO)
**     Description :
**         This method clears (sets to zero) the specified bit
**         of the output value.
**         [ It is the same as "PutBit(Bit,FALSE);" ]
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit to clear (0 to 3)
**     Returns     : Nothing
** ===================================================================
*/
#define PTES_ClrBit(Bit) ((void)BitsIoLdd4_ClrBit(BitsIoLdd4_DeviceData, (Bit)))

/*
** ===================================================================
**     Method      :  PTES_NegBit (component BitsIO)
**     Description :
**         This method negates (inverts) the specified bit of the
**         output value.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit to invert (0 to 31)
**     Returns     : Nothing
** ===================================================================
*/
#define PTES_NegBit(Bit) ((void)BitsIoLdd4_NegBit(BitsIoLdd4_DeviceData, (Bit)))

/* END PTES. */

#ifdef __cplusplus
}  /* extern "C" */
#endif 

#endif 
/* ifndef __PTES_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
