################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../Generated_Code/ADC0_chanells.c \
../Generated_Code/ADC1_chanells.c \
../Generated_Code/ASerialLdd1.c \
../Generated_Code/AdcLdd1.c \
../Generated_Code/AdcLdd2.c \
../Generated_Code/BIT_PTC.c \
../Generated_Code/BackLight.c \
../Generated_Code/Bit1.c \
../Generated_Code/BitIoLdd10.c \
../Generated_Code/BitIoLdd11.c \
../Generated_Code/BitIoLdd12.c \
../Generated_Code/BitIoLdd13.c \
../Generated_Code/BitIoLdd14.c \
../Generated_Code/BitIoLdd15.c \
../Generated_Code/BitIoLdd16.c \
../Generated_Code/BitIoLdd17.c \
../Generated_Code/BitIoLdd18.c \
../Generated_Code/BitIoLdd19.c \
../Generated_Code/BitIoLdd2.c \
../Generated_Code/BitIoLdd20.c \
../Generated_Code/BitIoLdd21.c \
../Generated_Code/BitIoLdd22.c \
../Generated_Code/BitIoLdd23.c \
../Generated_Code/BitIoLdd24.c \
../Generated_Code/BitIoLdd25.c \
../Generated_Code/BitIoLdd3.c \
../Generated_Code/BitIoLdd4.c \
../Generated_Code/BitIoLdd5.c \
../Generated_Code/BitIoLdd6.c \
../Generated_Code/BitIoLdd7.c \
../Generated_Code/BitIoLdd8.c \
../Generated_Code/BitIoLdd9.c \
../Generated_Code/BitsIoLdd1.c \
../Generated_Code/BitsIoLdd2.c \
../Generated_Code/BitsIoLdd3.c \
../Generated_Code/BitsIoLdd4.c \
../Generated_Code/BitsIoLdd5.c \
../Generated_Code/Bluethoot.c \
../Generated_Code/Buzzer.c \
../Generated_Code/CaptureLdd1.c \
../Generated_Code/CaptureLdd2.c \
../Generated_Code/Cpu.c \
../Generated_Code/DOWN.c \
../Generated_Code/ENTER.c \
../Generated_Code/FC321.c \
../Generated_Code/FC322.c \
../Generated_Code/IFsh1.c \
../Generated_Code/IntFlashLdd1.c \
../Generated_Code/LCD_0.c \
../Generated_Code/LCD_1.c \
../Generated_Code/LCD_2.c \
../Generated_Code/LCD_3.c \
../Generated_Code/LCD_4.c \
../Generated_Code/LCD_5.c \
../Generated_Code/LCD_6.c \
../Generated_Code/LCD_7.c \
../Generated_Code/Lcd_E.c \
../Generated_Code/Lcd_RS.c \
../Generated_Code/Lcd_RW.c \
../Generated_Code/MENU0.c \
../Generated_Code/PE_LDD.c \
../Generated_Code/PTB.c \
../Generated_Code/PTB9.c \
../Generated_Code/PTC.c \
../Generated_Code/PTC13_14_15.c \
../Generated_Code/PTC18.c \
../Generated_Code/PTE1.c \
../Generated_Code/PTE24.c \
../Generated_Code/PTES.c \
../Generated_Code/PowerOnOff.c \
../Generated_Code/PwmLdd1.c \
../Generated_Code/RPM.c \
../Generated_Code/RTC1.c \
../Generated_Code/RealTimeLdd1.c \
../Generated_Code/RealTimeLdd2.c \
../Generated_Code/Sens_vel.c \
../Generated_Code/TI1.c \
../Generated_Code/TU1.c \
../Generated_Code/TU2.c \
../Generated_Code/TU3.c \
../Generated_Code/TU4.c \
../Generated_Code/TU5.c \
../Generated_Code/TU6.c \
../Generated_Code/TU7.c \
../Generated_Code/Teclado.c \
../Generated_Code/TimeDateLdd1.c \
../Generated_Code/TimerIntLdd1.c \
../Generated_Code/TimerIntLdd2.c \
../Generated_Code/TmDt1.c \
../Generated_Code/UP.c \
../Generated_Code/Vectors.c \
../Generated_Code/WDog1.c \
../Generated_Code/WatchDogLdd1.c \
../Generated_Code/pta19.c \
../Generated_Code/pta5.c 

OBJS += \
./Generated_Code/ADC0_chanells.o \
./Generated_Code/ADC1_chanells.o \
./Generated_Code/ASerialLdd1.o \
./Generated_Code/AdcLdd1.o \
./Generated_Code/AdcLdd2.o \
./Generated_Code/BIT_PTC.o \
./Generated_Code/BackLight.o \
./Generated_Code/Bit1.o \
./Generated_Code/BitIoLdd10.o \
./Generated_Code/BitIoLdd11.o \
./Generated_Code/BitIoLdd12.o \
./Generated_Code/BitIoLdd13.o \
./Generated_Code/BitIoLdd14.o \
./Generated_Code/BitIoLdd15.o \
./Generated_Code/BitIoLdd16.o \
./Generated_Code/BitIoLdd17.o \
./Generated_Code/BitIoLdd18.o \
./Generated_Code/BitIoLdd19.o \
./Generated_Code/BitIoLdd2.o \
./Generated_Code/BitIoLdd20.o \
./Generated_Code/BitIoLdd21.o \
./Generated_Code/BitIoLdd22.o \
./Generated_Code/BitIoLdd23.o \
./Generated_Code/BitIoLdd24.o \
./Generated_Code/BitIoLdd25.o \
./Generated_Code/BitIoLdd3.o \
./Generated_Code/BitIoLdd4.o \
./Generated_Code/BitIoLdd5.o \
./Generated_Code/BitIoLdd6.o \
./Generated_Code/BitIoLdd7.o \
./Generated_Code/BitIoLdd8.o \
./Generated_Code/BitIoLdd9.o \
./Generated_Code/BitsIoLdd1.o \
./Generated_Code/BitsIoLdd2.o \
./Generated_Code/BitsIoLdd3.o \
./Generated_Code/BitsIoLdd4.o \
./Generated_Code/BitsIoLdd5.o \
./Generated_Code/Bluethoot.o \
./Generated_Code/Buzzer.o \
./Generated_Code/CaptureLdd1.o \
./Generated_Code/CaptureLdd2.o \
./Generated_Code/Cpu.o \
./Generated_Code/DOWN.o \
./Generated_Code/ENTER.o \
./Generated_Code/FC321.o \
./Generated_Code/FC322.o \
./Generated_Code/IFsh1.o \
./Generated_Code/IntFlashLdd1.o \
./Generated_Code/LCD_0.o \
./Generated_Code/LCD_1.o \
./Generated_Code/LCD_2.o \
./Generated_Code/LCD_3.o \
./Generated_Code/LCD_4.o \
./Generated_Code/LCD_5.o \
./Generated_Code/LCD_6.o \
./Generated_Code/LCD_7.o \
./Generated_Code/Lcd_E.o \
./Generated_Code/Lcd_RS.o \
./Generated_Code/Lcd_RW.o \
./Generated_Code/MENU0.o \
./Generated_Code/PE_LDD.o \
./Generated_Code/PTB.o \
./Generated_Code/PTB9.o \
./Generated_Code/PTC.o \
./Generated_Code/PTC13_14_15.o \
./Generated_Code/PTC18.o \
./Generated_Code/PTE1.o \
./Generated_Code/PTE24.o \
./Generated_Code/PTES.o \
./Generated_Code/PowerOnOff.o \
./Generated_Code/PwmLdd1.o \
./Generated_Code/RPM.o \
./Generated_Code/RTC1.o \
./Generated_Code/RealTimeLdd1.o \
./Generated_Code/RealTimeLdd2.o \
./Generated_Code/Sens_vel.o \
./Generated_Code/TI1.o \
./Generated_Code/TU1.o \
./Generated_Code/TU2.o \
./Generated_Code/TU3.o \
./Generated_Code/TU4.o \
./Generated_Code/TU5.o \
./Generated_Code/TU6.o \
./Generated_Code/TU7.o \
./Generated_Code/Teclado.o \
./Generated_Code/TimeDateLdd1.o \
./Generated_Code/TimerIntLdd1.o \
./Generated_Code/TimerIntLdd2.o \
./Generated_Code/TmDt1.o \
./Generated_Code/UP.o \
./Generated_Code/Vectors.o \
./Generated_Code/WDog1.o \
./Generated_Code/WatchDogLdd1.o \
./Generated_Code/pta19.o \
./Generated_Code/pta5.o 

C_DEPS += \
./Generated_Code/ADC0_chanells.d \
./Generated_Code/ADC1_chanells.d \
./Generated_Code/ASerialLdd1.d \
./Generated_Code/AdcLdd1.d \
./Generated_Code/AdcLdd2.d \
./Generated_Code/BIT_PTC.d \
./Generated_Code/BackLight.d \
./Generated_Code/Bit1.d \
./Generated_Code/BitIoLdd10.d \
./Generated_Code/BitIoLdd11.d \
./Generated_Code/BitIoLdd12.d \
./Generated_Code/BitIoLdd13.d \
./Generated_Code/BitIoLdd14.d \
./Generated_Code/BitIoLdd15.d \
./Generated_Code/BitIoLdd16.d \
./Generated_Code/BitIoLdd17.d \
./Generated_Code/BitIoLdd18.d \
./Generated_Code/BitIoLdd19.d \
./Generated_Code/BitIoLdd2.d \
./Generated_Code/BitIoLdd20.d \
./Generated_Code/BitIoLdd21.d \
./Generated_Code/BitIoLdd22.d \
./Generated_Code/BitIoLdd23.d \
./Generated_Code/BitIoLdd24.d \
./Generated_Code/BitIoLdd25.d \
./Generated_Code/BitIoLdd3.d \
./Generated_Code/BitIoLdd4.d \
./Generated_Code/BitIoLdd5.d \
./Generated_Code/BitIoLdd6.d \
./Generated_Code/BitIoLdd7.d \
./Generated_Code/BitIoLdd8.d \
./Generated_Code/BitIoLdd9.d \
./Generated_Code/BitsIoLdd1.d \
./Generated_Code/BitsIoLdd2.d \
./Generated_Code/BitsIoLdd3.d \
./Generated_Code/BitsIoLdd4.d \
./Generated_Code/BitsIoLdd5.d \
./Generated_Code/Bluethoot.d \
./Generated_Code/Buzzer.d \
./Generated_Code/CaptureLdd1.d \
./Generated_Code/CaptureLdd2.d \
./Generated_Code/Cpu.d \
./Generated_Code/DOWN.d \
./Generated_Code/ENTER.d \
./Generated_Code/FC321.d \
./Generated_Code/FC322.d \
./Generated_Code/IFsh1.d \
./Generated_Code/IntFlashLdd1.d \
./Generated_Code/LCD_0.d \
./Generated_Code/LCD_1.d \
./Generated_Code/LCD_2.d \
./Generated_Code/LCD_3.d \
./Generated_Code/LCD_4.d \
./Generated_Code/LCD_5.d \
./Generated_Code/LCD_6.d \
./Generated_Code/LCD_7.d \
./Generated_Code/Lcd_E.d \
./Generated_Code/Lcd_RS.d \
./Generated_Code/Lcd_RW.d \
./Generated_Code/MENU0.d \
./Generated_Code/PE_LDD.d \
./Generated_Code/PTB.d \
./Generated_Code/PTB9.d \
./Generated_Code/PTC.d \
./Generated_Code/PTC13_14_15.d \
./Generated_Code/PTC18.d \
./Generated_Code/PTE1.d \
./Generated_Code/PTE24.d \
./Generated_Code/PTES.d \
./Generated_Code/PowerOnOff.d \
./Generated_Code/PwmLdd1.d \
./Generated_Code/RPM.d \
./Generated_Code/RTC1.d \
./Generated_Code/RealTimeLdd1.d \
./Generated_Code/RealTimeLdd2.d \
./Generated_Code/Sens_vel.d \
./Generated_Code/TI1.d \
./Generated_Code/TU1.d \
./Generated_Code/TU2.d \
./Generated_Code/TU3.d \
./Generated_Code/TU4.d \
./Generated_Code/TU5.d \
./Generated_Code/TU6.d \
./Generated_Code/TU7.d \
./Generated_Code/Teclado.d \
./Generated_Code/TimeDateLdd1.d \
./Generated_Code/TimerIntLdd1.d \
./Generated_Code/TimerIntLdd2.d \
./Generated_Code/TmDt1.d \
./Generated_Code/UP.d \
./Generated_Code/Vectors.d \
./Generated_Code/WDog1.d \
./Generated_Code/WatchDogLdd1.d \
./Generated_Code/pta19.d \
./Generated_Code/pta5.d 


# Each subdirectory must supply rules for building sources it contributes
Generated_Code/%.o: ../Generated_Code/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross ARM GNU C Compiler'
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -O0 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections  -g3 -I"C:/Users/Rosimar/workspace.kds/Ms_200/Static_Code/PDD" -I"C:/Users/Rosimar/workspace.kds/Ms_200/Static_Code/IO_Map" -I"C:/Users/Rosimar/workspace.kds/Ms_200/Sources" -I"C:/Users/Rosimar/workspace.kds/Ms_200/Generated_Code" -std=c99 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


